---
title: "Analysis"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=6, fig.height=4, fig.path='../images/', dev=c('png', 'pdf'))

require(sqldf)
require(ggplot2)
require(xtable)
require(VennDiagram)
require(ggvenn)
```


## Load the Complete Dataset for Study 1

```{r}
ds <- read.csv("allreportResults.csv", head=T, sep=",")

staticAnalysis <- sqldf("select tool, count(distinct app) totalWith
                        from ds 
                        where malware = 1 and static = 1 and tool != 'flowdroid'
                        group by tool")

withoutStaticAnalysis <-  sqldf("select tool, count(distinct app) totalWithout
                                  from ds 
                                  where malware = 1 and static = 0
                                  group by tool")

res <- merge(staticAnalysis, withoutStaticAnalysis, all.x=T)

res[is.na(res)] <- 0
res["Improvement"] = (res$totalWith  - res$totalWithout) * 100 / res$totalWith 
xtable(res[order(-res$totalWith),])
```

## Compare the performance of the different tools (with DroidFax)

```{r, venn-plot-s1}

colnames(ds)
sets <- sqldf("select tool, app, count(*) total 
                  from ds 
                  where malware = 1 and static = 1
                  group by tool, app")

monkey = sets[sets$tool=="monkey", c("app")]
humanoid = sets[sets$tool=="humanoid", c("app")]
droidmate = sets[sets$tool=="droidmate", c("app")]
droidbot = sets[sets$tool=="droidbot", c("app")]
joker = sets[sets$tool=="joke", c("app")]

x <- list(
  Monkey = monkey,
  Humanoid = humanoid, 
  DroidMate = droidmate,
  DroidBot = droidbot
)

ggvenn(
 x,
 fill_color = c("#0073C2FF", "#EFC000FF", "#868686FF", "#CD534CFF","#CD534CAA"),
   stroke_size = 0.5, set_name_size = 4, text_size=2
)
```

## Total of malwares detected by at least one tool

```{r}
sqldf("select count(distinct app) from ds where malware = 1")
```

## Load the Complete Dataset for Study 2

```{r}
ds <- read.csv("allreportResults.csv", head=T, sep=",")
```

## Compare the performance of FlowDroid and DroidFax (Joker tool)

```{r, venn-plot-s2}
sets <- sqldf("select tool, app 
                  from ds 
                  where malware = 1 
                    and (tool='flowdroid' or tool = 'joke')")

notDetected <- sqldf("select distinct app from ds where 
                      app not in (select app from sets)")


flowdroid = sets[sets$tool=="flowdroid", c("app")]
droidfax = sets[sets$tool=="joke", c("app")]
notDetected = sets[, c("app")]

x <- list(
  FlowDroid = flowdroid,
  DroidFax = droidfax
)

ggvenn(
 x,
 fill_color = c("#0073C2FF", "#EFC000FF"),
   stroke_size = 0.5, set_name_size = 4, text_size=2.5
)

```